# Generated by Django 6.0.5 on 2026-05-19 23:10

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("pghistory", "0007_auto_20250421_0444"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbsenceJustification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="data da falta")),
                ("reason", models.TextField(verbose_name="motivo")),
                (
                    "file_url",
                    models.URLField(blank=True, verbose_name="comprovante (URL)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("APPROVED", "Aprovado"),
                            ("REJECTED", "Rejeitado"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_justifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="revisor",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="justifications",
                        to="academic.student",
                        verbose_name="aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "justificativa de falta",
                "verbose_name_plural": "justificativas de falta",
                "ordering": ["-date", "student"],
            },
        ),
        migrations.CreateModel(
            name="AbsenceJustificationEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                ("date", models.DateField(verbose_name="data da falta")),
                ("reason", models.TextField(verbose_name="motivo")),
                (
                    "file_url",
                    models.URLField(blank=True, verbose_name="comprovante (URL)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("APPROVED", "Aprovado"),
                            ("REJECTED", "Rejeitado"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="attendance.absencejustification",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="revisor",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="academic.student",
                        verbose_name="aluno",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="data")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Presente"),
                            ("ABSENT", "Ausente"),
                            ("JUSTIFIED", "Justificado"),
                        ],
                        default="ABSENT",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "observer",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["MONITOR", "COORDENADOR"]},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_attendances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="observador",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_records",
                        to="academic.student",
                        verbose_name="aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de chamada",
                "verbose_name_plural": "registros de chamada",
                "ordering": ["-date", "student"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecordEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                ("date", models.DateField(verbose_name="data")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Presente"),
                            ("ABSENT", "Ausente"),
                            ("JUSTIFIED", "Justificado"),
                        ],
                        default="ABSENT",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "observer",
                    models.ForeignKey(
                        db_constraint=False,
                        limit_choices_to={"role__in": ["MONITOR", "COORDENADOR"]},
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="observador",
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="attendance.attendancerecord",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="academic.student",
                        verbose_name="aluno",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="absencejustification",
            trigger=pgtrigger.compiler.Trigger(
                name="justification_created_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "attendance_absencejustificationevent" ("created_at", "date", "file_url", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason", "reviewer_id", "status", "student_id", "updated_at") VALUES (NEW."created_at", NEW."date", NEW."file_url", NEW."id", _pgh_attach_context(), NOW(), \'justification_created\', NEW."id", NEW."reason", NEW."reviewer_id", NEW."status", NEW."student_id", NEW."updated_at"); RETURN NULL;',
                    hash="d96b2c18f3b7fa74052e8941e1c27e13589eb72c",
                    operation="INSERT",
                    pgid="pgtrigger_justification_created_insert_02488",
                    table="attendance_absencejustification",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="absencejustification",
            trigger=pgtrigger.compiler.Trigger(
                name="justification_updated_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "attendance_absencejustificationevent" ("created_at", "date", "file_url", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason", "reviewer_id", "status", "student_id", "updated_at") VALUES (NEW."created_at", NEW."date", NEW."file_url", NEW."id", _pgh_attach_context(), NOW(), \'justification_updated\', NEW."id", NEW."reason", NEW."reviewer_id", NEW."status", NEW."student_id", NEW."updated_at"); RETURN NULL;',
                    hash="88e0893e3b9aa867e651fd5d0fa9488fc5b812c4",
                    operation="UPDATE",
                    pgid="pgtrigger_justification_updated_update_88011",
                    table="attendance_absencejustification",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="absencejustification",
            trigger=pgtrigger.compiler.Trigger(
                name="justification_deleted_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "attendance_absencejustificationevent" ("created_at", "date", "file_url", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason", "reviewer_id", "status", "student_id", "updated_at") VALUES (OLD."created_at", OLD."date", OLD."file_url", OLD."id", _pgh_attach_context(), NOW(), \'justification_deleted\', OLD."id", OLD."reason", OLD."reviewer_id", OLD."status", OLD."student_id", OLD."updated_at"); RETURN NULL;',
                    hash="f4a8c62674bb9f74598ae19d3f2bb39f8f94b6a7",
                    operation="DELETE",
                    pgid="pgtrigger_justification_deleted_delete_8ddb3",
                    table="attendance_absencejustification",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancerecord",
            constraint=models.UniqueConstraint(
                fields=("student", "date"), name="unique_attendance_per_student_per_day"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="attendancerecord",
            trigger=pgtrigger.compiler.Trigger(
                name="attendance_created_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "attendance_attendancerecordevent" ("created_at", "date", "id", "observer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "student_id", "updated_at") VALUES (NEW."created_at", NEW."date", NEW."id", NEW."observer_id", _pgh_attach_context(), NOW(), \'attendance_created\', NEW."id", NEW."status", NEW."student_id", NEW."updated_at"); RETURN NULL;',
                    hash="5a10187fd0e15c4714570033e3e99c1edabc351e",
                    operation="INSERT",
                    pgid="pgtrigger_attendance_created_insert_60b05",
                    table="attendance_attendancerecord",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="attendancerecord",
            trigger=pgtrigger.compiler.Trigger(
                name="attendance_updated_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "attendance_attendancerecordevent" ("created_at", "date", "id", "observer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "student_id", "updated_at") VALUES (NEW."created_at", NEW."date", NEW."id", NEW."observer_id", _pgh_attach_context(), NOW(), \'attendance_updated\', NEW."id", NEW."status", NEW."student_id", NEW."updated_at"); RETURN NULL;',
                    hash="4f9dab2759f6f132940a5103907cab741833eee9",
                    operation="UPDATE",
                    pgid="pgtrigger_attendance_updated_update_38d12",
                    table="attendance_attendancerecord",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="attendancerecord",
            trigger=pgtrigger.compiler.Trigger(
                name="attendance_deleted_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "attendance_attendancerecordevent" ("created_at", "date", "id", "observer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "student_id", "updated_at") VALUES (OLD."created_at", OLD."date", OLD."id", OLD."observer_id", _pgh_attach_context(), NOW(), \'attendance_deleted\', OLD."id", OLD."status", OLD."student_id", OLD."updated_at"); RETURN NULL;',
                    hash="acf31f1a4a4f7a8a91c4397107a595b52a6f8b92",
                    operation="DELETE",
                    pgid="pgtrigger_attendance_deleted_delete_e4ee4",
                    table="attendance_attendancerecord",
                    when="AFTER",
                ),
            ),
        ),
    ]
