# Generated by Django 6.0.5 on 2026-05-20 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='observer',
            field=models.ForeignKey(limit_choices_to={'role__in': ['MONITOR', 'COORDENADOR']}, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL, verbose_name='monitor'),
        ),
        migrations.AlterField(
            model_name='attendancerecordevent',
            name='observer',
            field=models.ForeignKey(db_constraint=False, limit_choices_to={'role__in': ['MONITOR', 'COORDENADOR']}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='monitor'),
        ),
    ]
