# Generated by Django 6.0.5 on 2026-05-20 15:13

import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('attendance', '0002_alter_attendancerecord_observer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='attendancerecord',
            name='attendance_created_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='attendancerecord',
            name='attendance_updated_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='attendancerecord',
            name='attendance_deleted_delete',
        ),
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='unique_attendance_per_student_per_day',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='period',
            field=models.CharField(choices=[('BEFORE_BREAK', 'Antes do Intervalo'), ('AFTER_BREAK', 'Depois do Intervalo')], default='BEFORE_BREAK', max_length=12, verbose_name='período'),
        ),
        migrations.AddField(
            model_name='attendancerecordevent',
            name='period',
            field=models.CharField(choices=[('BEFORE_BREAK', 'Antes do Intervalo'), ('AFTER_BREAK', 'Depois do Intervalo')], default='BEFORE_BREAK', max_length=12, verbose_name='período'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attendancerecord',
            trigger=pgtrigger.compiler.Trigger(name='attendance_created_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "attendance_attendancerecordevent" ("created_at", "date", "id", "observer_id", "period", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "student_id", "updated_at") VALUES (NEW."created_at", NEW."date", NEW."id", NEW."observer_id", NEW."period", _pgh_attach_context(), NOW(), \'attendance_created\', NEW."id", NEW."status", NEW."student_id", NEW."updated_at"); RETURN NULL;', hash='24ea3cb19097ec3557d4fc969fd47db2386a7cbe', operation='INSERT', pgid='pgtrigger_attendance_created_insert_60b05', table='attendance_attendancerecord', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attendancerecord',
            trigger=pgtrigger.compiler.Trigger(name='attendance_updated_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "attendance_attendancerecordevent" ("created_at", "date", "id", "observer_id", "period", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "student_id", "updated_at") VALUES (NEW."created_at", NEW."date", NEW."id", NEW."observer_id", NEW."period", _pgh_attach_context(), NOW(), \'attendance_updated\', NEW."id", NEW."status", NEW."student_id", NEW."updated_at"); RETURN NULL;', hash='6a52388c457c96bfc300b9096484925f7c7b4b05', operation='UPDATE', pgid='pgtrigger_attendance_updated_update_38d12', table='attendance_attendancerecord', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='attendancerecord',
            trigger=pgtrigger.compiler.Trigger(name='attendance_deleted_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "attendance_attendancerecordevent" ("created_at", "date", "id", "observer_id", "period", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "student_id", "updated_at") VALUES (OLD."created_at", OLD."date", OLD."id", OLD."observer_id", OLD."period", _pgh_attach_context(), NOW(), \'attendance_deleted\', OLD."id", OLD."status", OLD."student_id", OLD."updated_at"); RETURN NULL;', hash='8b6c0badca51a03cd98ddecad1adaa2ef3a4f6bb', operation='DELETE', pgid='pgtrigger_attendance_deleted_delete_e4ee4', table='attendance_attendancerecord', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('student', 'date', 'period'), name='unique_attendance_per_student_per_day_per_period'),
        ),
    ]
