# Generated by Django 6.0.5 on 2026-05-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_add_period_to_attendance_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='period',
            field=models.CharField(choices=[('BEFORE_BREAK', 'Antes do Intervalo'), ('AFTER_BREAK', 'Depois do Intervalo')], max_length=12, verbose_name='período'),
        ),
        migrations.AlterField(
            model_name='attendancerecordevent',
            name='period',
            field=models.CharField(choices=[('BEFORE_BREAK', 'Antes do Intervalo'), ('AFTER_BREAK', 'Depois do Intervalo')], max_length=12, verbose_name='período'),
        ),
    ]
